language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -uroot -e 'create database eloquent_only;'
  - mysql -uroot -e 'use eloquent_only; CREATE TABLE users ( `id` int(11) , name varchar(11));'

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit
